server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /fastpay-admin/;
    }

    location /fastpay-admin/ {
        try_files $uri $uri/ /fastpay-admin/index.html;
    }

    location /fastpay-server/ {
        proxy_pass http://fast_pay_server:7001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
